### ISSUE TITLE
components

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/create-choo-app#9]
Was thinking including `nanocomponent` might make sense. Perhaps a lil "hi there" screen with a main route and 404 route set up, including a lil header or smth. Then also include [assert-snapshot](https://github.com/yoshuawuyts/assert-snapshot/) with `tape` so folks can figure out how to do UI testing right.

Depends on new nanocomponent.

cc/ @bcomnes 

### todo
- [ ]  create header component (`components/header.js`)
- [ ] setup testing (`test/index.js`, `test/header.js`)
- [ ] create a `test-save` script (or similar) to save the new snapshot

**Comment by bcomnes** [comment]
+1 to adding nanocomponent by default.

**Comment by bcomnes** [comment]
Also setting up UI testing would be ace.   I still need to sort out how to do that.

**Comment by niallobrien** [comment]
The default view generated mentions that a `component` folder is included, however, it's not. Are there still plans to add this? Thanks.

![image](https://user-images.githubusercontent.com/1525669/40193724-0313e2c2-5a00-11e8-838e-f1c1812736c1.png)
![image](https://user-images.githubusercontent.com/1525669/40193747-15fde144-5a00-11e8-8965-7c942ddae014.png)
